import { initializeApp } from "https://www.gstatic.com/firebasejs/11.1.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, sendPasswordResetEmail, signOut } from "https://www.gstatic.com/firebasejs/11.1.0/firebase-auth.js";
import { getFirestore, doc, getDoc, getDocs, collection, query, where, orderBy, limit, onSnapshot, updateDoc, setDoc, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.1.0/firebase-firestore.js";
import { getFunctions, httpsCallable } from "https://www.gstatic.com/firebasejs/11.1.0/firebase-functions.js";
import { initializeAppCheck, ReCaptchaV3Provider } from "https://www.gstatic.com/firebasejs/11.1.0/firebase-app-check.js";
import { firebaseConfig, functionsRegion, recaptchaSiteKey } from "./firebase-config.js";

const app = initializeApp(firebaseConfig);
if (recaptchaSiteKey) initializeAppCheck(app, { provider: new ReCaptchaV3Provider(recaptchaSiteKey), isTokenAutoRefreshEnabled: true });
const auth = getAuth(app);
const db = getFirestore(app);
const functions = getFunctions(app, functionsRegion);

const $ = id => document.getElementById(id);
const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money = v => `₹${Number(v || 0).toLocaleString("en-IN")}`;
const toDate = v => v?.toDate ? v.toDate() : null;
const dateText = v => toDate(v)?.toLocaleString("en-IN", { day:"numeric", month:"short", year:"numeric", hour:"numeric", minute:"2-digit" }) || "—";
const timeAgo = v => { const d=toDate(v); if(!d)return "—"; const m=Math.max(0,Math.floor((Date.now()-d.getTime())/60000)); return m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`; };
const bookingRef = id => `RIT-${String(id || "").slice(-6).toUpperCase()}`;
const toast = text => { $("toast").textContent=text; $("toast").classList.add("show"); setTimeout(()=>$("toast").classList.remove("show"),2800); };
const friendly = e => { const c=e?.code||""; if(c.includes("permission-denied"))return "This owner account does not have permission for that action."; if(c.includes("failed-precondition"))return e.message?.replace(/^FirebaseError:\s*/i,"")||"This action is not allowed in the current booking state."; if(c.includes("invalid-credential"))return "Incorrect email or password."; return e?.message?.replace(/^Firebase:\s*/i,"").replace(/^FirebaseError:\s*/i,"") || "This action could not be completed."; };

const NAV = [
  ["overview","Overview","⌂"],["bookings","Bookings","▤"],["controlrooms","Control Rooms","▣"],["support","Support","◎"],["reelos","Reelos","◉"],
  ["earnings","Earnings","₹"],["content","Content","□"],["payments","Payments","▧"],["refunds","Refunds","↩"],["sos","SOS Alerts","△"],
  ["reports","Reports","⚑"],["feedback","Feedback","☆"],["accounts","Accounts","◇"],["settings","Settings","⚙"]
];
let activePage="overview", bookingCache=[], activeBookingId=null, drawerUnsubs=[], pageUnsub=null;

$("nav").innerHTML=NAV.map(([id,label,icon])=>`<button class="nav-button" data-page="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join("");
$("nav").onclick=e=>{const b=e.target.closest("[data-page]");if(b)loadPage(b.dataset.page);};
$("sign-out").onclick=()=>signOut(auth);
$("forgot-password").onclick=async()=>{const email=$("email").value.trim();if(!email)return setAuth("Enter your admin email first.");try{await sendPasswordResetEmail(auth,email);setAuth("Password reset email sent.",false);}catch(e){setAuth(friendly(e));}};
$("login-form").onsubmit=async e=>{e.preventDefault();setAuth("Signing in…",false);try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value);}catch(err){setAuth(friendly(err));}};
$("close-drawer").onclick=closeDrawer;
$("close-modal").onclick=()=>$("modal").close();
$("modal").onclick=e=>{if(e.target===$("modal"))$("modal").close();};
$("search-button").onclick=runGlobalSearch;
$("global-search").addEventListener("keydown",e=>{if(e.key==="Enter")runGlobalSearch();});
$("refresh-all").onclick=()=>loadPage(activePage);
if($("today-chip")) $("today-chip").textContent=new Date().toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"});
function setAuth(text,error=true){$("auth-message").textContent=text;$("auth-message").style.color=error?"#d73a49":"#12885f";}

onAuthStateChanged(auth,async user=>{
  if(!user){$("app-view").classList.add("hidden");$("auth-view").classList.remove("hidden");return;}
  try{
    const admin=await getDoc(doc(db,"admins",user.uid));
    if(!admin.exists()||admin.data().active!==true){await signOut(auth);return setAuth("This account is not an active Reel It administrator.");}
    $("auth-view").classList.add("hidden");$("app-view").classList.remove("hidden");$("admin-email").textContent=user.email||"Owner";
    await loadPage(activePage);
  }catch(e){await signOut(auth);setAuth(friendly(e));}
});

const PAGE_META={
  overview:["Overview","Real-time overview of your platform"],bookings:["Bookings","All bookings and lifecycle states"],controlrooms:["Control Rooms","Bookings that need direct operational intervention"],support:["Support","Customer and Reelo conversations linked to bookings"],
  reelos:["Reelos","Availability, verification and editing eligibility"],earnings:["Earnings","Reelo earnings and payout readiness"],content:["Content","Pending uploads, delivery reviews and disputes"],payments:["Payments","Captured payments and exceptions"],refunds:["Refunds","Refund requests and provider exceptions"],
  sos:["SOS Alerts","Safety alerts requiring immediate attention"],reports:["Reports","User reports and trust & safety cases"],feedback:["Feedback","Customer and Reelo feedback"],accounts:["Accounts","Deletion requests and account operations"],settings:["Settings","Admin audit and system controls"]
};
async function loadPage(id){
  if(pageUnsub){pageUnsub();pageUnsub=null;} closeDrawer(false);activePage=id;document.querySelectorAll("[data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===id));
  const [title,sub]=PAGE_META[id]||["Operations",""];$("page-title").textContent=title;$("page-subtitle").textContent=sub;$("content").innerHTML='<div class="loading">Loading live operations…</div>';
  try{if(id==="overview")await loadOverview();else if(id==="bookings"||id==="controlrooms")await loadBookings();else if(id==="support")await loadSupport();else if(id==="reelos")await loadReelos();else if(id==="content")await loadContent();else if(id==="payments"||id==="earnings")await loadPayments();else if(id==="refunds")await loadRefunds();else if(id==="sos")await loadSOS();else if(id==="reports"||id==="feedback")await loadReports();else if(id==="accounts")await loadAccounts();else if(id==="settings")await loadAudit();}
  catch(e){$("content").innerHTML=`<div class="panel"><div class="empty"><strong>Could not load this section.</strong><br><span class="sub">${esc(friendly(e))}</span><br><br><button class="btn secondary" id="retry">Try again</button></div></div>`;$("retry").onclick=()=>loadPage(id);}
}

function deliveryState(x){
  if(x.deliveryDisputed===true)return {key:"dispute",label:"Disputed",tone:"red",detail:"Payout paused"};
  if(x.deliveryStatus==="customer_confirmed")return {key:"confirmed",label:"Accepted",tone:"green",detail:"Customer confirmed"};
  if(x.deliveryStatus==="delivered")return {key:"approval",label:"Pending approval",tone:"blue",detail:"Waiting for customer"};
  if(x.deliveryStatus==="uploading")return {key:"uploading",label:"Uploading",tone:"orange",detail:"Reelo uploading"};
  if(x.status==="completed" || x.deliveryStatus==="pending_upload")return {key:"pending_upload",label:"Pending upload",tone:"orange",detail:deadlineText(x)};
  return {key:"none",label:"Not started",tone:"",detail:"—"};
}
function deadlineText(x){const d=toDate(x.deliveryDueAt||x.deliveryDeadline);if(!d)return x.deliveryType==="edited"?"48h delivery":"24h delivery";const diff=d.getTime()-Date.now();if(diff<0){const h=Math.ceil(Math.abs(diff)/3600000);return `${h}h overdue`;}const h=Math.floor(diff/3600000),m=Math.floor((diff%3600000)/60000);return `Due in ${h}h ${m}m`;}
function sessionState(x){const map={searching:["Searching","blue"],accepted:["Accepted","blue"],arrived:["Arrived","orange"],in_progress:["In progress","orange"],completed:["Completed","green"],cancelled:["Cancelled","red"],payment_pending:["Payment pending","orange"]};const [label,tone]=map[x.status]||[String(x.status||"Unknown").replaceAll("_"," "),""];return {label,tone};}
function paymentState(x){if(["captured","paid"].includes(x.paymentStatus))return {label:"Paid",tone:"green"};if(["failed","manual_review_required"].includes(x.paymentStatus)||x.operationalAttentionType==="payment_review")return {label:"Review",tone:"red"};return {label:String(x.paymentStatus||"Pending").replaceAll("_"," "),tone:"orange"};}
function needsAttention(x){const del=deliveryState(x);if(x.deliveryDisputed===true)return true;if(del.key==="pending_upload"&&del.detail.includes("overdue"))return true;if(x.paymentStatus==="failed"||x.refundStatus==="manual_review_required"||x.operationalAttention===true)return true;if(x.status==="searching"&&toDate(x.requestExpiresAt)?.getTime()<Date.now())return true;if(x.status==="completed"&&!x.deliveryStatus)return true;return false;}
function statusHtml(label,tone=""){return `<span class="status ${tone}"><i class="dot"></i>${esc(label)}</span>`;}
function bookingSearchText(id,x){return [id,bookingRef(id),x.occasion,x.customerName,x.customerEmail,x.customerId,x.reeloName,x.reeloEmail,x.reeloId,x.paymentReference,x.razorpayOrderId,x.location].filter(Boolean).join(" ").toLowerCase();}

async function fetchBookings(){const snap=await getDocs(query(collection(db,"bookings"),orderBy("updatedAt","desc"),limit(250)));bookingCache=snap.docs.map(d=>({id:d.id,...d.data()}));return bookingCache;}
async function loadOverview(){
  const [bookings,supportSnap,profilesSnap,sosSnap]=await Promise.all([fetchBookings(),getDocs(query(collection(db,"support_threads"),where("humanRequested","==",true))),getDocs(collection(db,"reelo_profiles")),getDocs(query(collection(db,"sos_alerts"),where("status","in",["active","acknowledged","escalated"]))) ]);
  const today=new Date();today.setHours(0,0,0,0);const todayBookings=bookings.filter(x=>toDate(x.createdAt)?.getTime()>=today.getTime());const revenue=todayBookings.filter(x=>["captured","paid"].includes(x.paymentStatus)).reduce((s,x)=>s+Number(x.customerPrice||x.price||0),0);const online=profilesSnap.docs.filter(d=>d.data().availability==="Online").length;const pending=bookings.filter(x=>deliveryState(x).key==="pending_upload").length;const attention=bookings.filter(needsAttention).length;
  $("content").innerHTML=`${metricsHtml([{label:"Today's Bookings",value:todayBookings.length,icon:"▣",sub:"Created today"},{label:"Revenue (Today)",value:money(revenue),icon:"₹",sub:"Captured payments",good:true},{label:"Active Reelos",value:online,icon:"◎",sub:"Online & available",good:true},{label:"Pending Upload",value:pending,icon:"⇧",sub:"Content still owed",warn:pending>0},{label:"Pending Actions",value:attention+supportSnap.size+sosSnap.size,icon:"!",sub:"Needs attention",warn:true}])}<div id="booking-panel"></div><div class="summary-grid"><div class="summary-card"><span>Bookings needing action</span><strong>${attention}</strong><a data-go="bookings">View all →</a></div><div class="summary-card"><span>Reelos online</span><strong>${online} / ${profilesSnap.size}</strong><a data-go="reelos">View Reelos →</a></div><div class="summary-card"><span>Human support waiting</span><strong>${supportSnap.size}</strong><a data-go="support">Open Support →</a></div></div>`;
  renderBookingPanel(bookings,"all");document.querySelectorAll("[data-go]").forEach(a=>a.onclick=()=>loadPage(a.dataset.go));
}
function metricsHtml(items){return `<div class="metrics">${items.map(i=>`<div class="metric"><div class="metric-head"><span class="metric-icon">${i.icon}</span>${esc(i.label)}</div><strong>${esc(i.value)}</strong><small class="${i.good?'good':i.warn?'warn':''}">${esc(i.sub)}</small></div>`).join("")}</div>`;}
function renderBookingPanel(bookings,initial="all"){
  const counts={all:bookings.length,pending_upload:bookings.filter(x=>deliveryState(x).key==="pending_upload").length,approval:bookings.filter(x=>deliveryState(x).key==="approval").length,payment:bookings.filter(x=>paymentState(x).tone==="red").length,cancelled:bookings.filter(x=>x.status==="cancelled").length,attention:bookings.filter(needsAttention).length};
  $("booking-panel").innerHTML=`<section class="panel"><div class="filter-tabs">${[["all","All"],["pending_upload","Pending Upload"],["approval","Pending Approval"],["payment","Payment Issues"],["cancelled","Cancellations"],["attention","Needs Attention"]].map(([k,l])=>`<button class="filter-tab ${k===initial?'active':''}" data-filter="${k}">${l}<b>${counts[k]||0}</b></button>`).join("")}</div><div class="table-tools"><div class="mini-search"><span>⌕</span><input id="booking-search" placeholder="Search booking ID, customer, Reelo, email, payment ID…"></div><button class="btn secondary" id="table-refresh">▥ Columns</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Booking</th><th>Customer</th><th>Reelo</th><th>Session</th><th>Delivery</th><th>Payment</th><th>Status</th><th>Actions</th></tr></thead><tbody id="booking-rows"></tbody></table></div><div class="table-footer"><span id="table-count">Showing bookings</span><div class="pager"><span>‹</span><span class="active">1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>›</span></div><span>10 / page ⌄</span></div></section>`;
  let filter=initial,term="";const apply=()=>{let rows=bookings;if(filter==="pending_upload")rows=rows.filter(x=>deliveryState(x).key==="pending_upload");else if(filter==="approval")rows=rows.filter(x=>deliveryState(x).key==="approval");else if(filter==="payment")rows=rows.filter(x=>paymentState(x).tone==="red");else if(filter==="cancelled")rows=rows.filter(x=>x.status==="cancelled");else if(filter==="attention")rows=rows.filter(needsAttention);if(term)rows=rows.filter(x=>bookingSearchText(x.id,x).includes(term));const shown=rows.slice(0,100);renderBookingRows(shown);if($("table-count"))$("table-count").textContent=`Showing 1 to ${Math.min(shown.length,10)} of ${rows.length} bookings`;};
  document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));apply();});$("booking-search").oninput=e=>{term=e.target.value.trim().toLowerCase();apply();};$("table-refresh").onclick=()=>toast("Column controls are coming next; all operational columns are visible now.");apply();
}
function renderBookingRows(rows){const body=$("booking-rows");if(!rows.length){body.innerHTML='<tr><td colspan="8"><div class="empty">No bookings match this view.</div></td></tr>';return;}body.innerHTML=rows.map(x=>{const del=deliveryState(x),ses=sessionState(x),pay=paymentState(x),att=needsAttention(x);return `<tr><td><button class="booking-link" data-booking="${esc(x.id)}">${bookingRef(x.id)}</button><span class="sub">${esc(x.occasion||"Booking")}</span></td><td><span class="person">${esc(x.customerName||x.customerEmail||"Customer")}</span><span class="sub">${esc(x.customerEmail||"")}</span></td><td><span class="person">${esc(x.reeloName||x.reeloEmail||"Not assigned")}</span><span class="sub">${esc(x.reeloEmail||"")}</span></td><td>${dateText(x.scheduledDateTime||x.createdAt)}<span class="sub">${esc(x.durationMinutes||0)} min</span></td><td>${statusHtml(del.label,del.tone)}<span class="sub">${esc(del.detail)}</span></td><td><span class="amount">${money(x.customerPrice||x.price)}</span><span class="sub ${pay.tone==='green'?'good':''}">${esc(pay.label)}</span></td><td>${att?statusHtml("Attention","red"):statusHtml(ses.label,ses.tone)}</td><td><div class="actions-cell"><button class="btn secondary" data-booking="${esc(x.id)}">View</button><button class="icon-btn" data-booking="${esc(x.id)}">⋮</button></div></td></tr>`;}).join("");body.querySelectorAll("[data-booking]").forEach(b=>b.onclick=()=>openBooking(b.dataset.booking));}

async function loadBookings(){const bookings=await fetchBookings();$("content").innerHTML='<div id="booking-panel"></div>';renderBookingPanel(bookings,"all");}

async function openBooking(id,tab="overview"){
  clearDrawerStreams();activeBookingId=id;const snap=await getDoc(doc(db,"bookings",id));if(!snap.exists())return toast("Booking not found.");const x={id,...snap.data()};
  $("drawer-title").textContent=`${bookingRef(id)} · ${x.occasion||"Booking"}`;$("drawer").classList.add("open");$("drawer").setAttribute("aria-hidden","false");
  await renderDrawer(x,tab);
}
function closeDrawer(clear=true){$("drawer").classList.remove("open");$("drawer").setAttribute("aria-hidden","true");clearDrawerStreams();if(clear)activeBookingId=null;}
function clearDrawerStreams(){drawerUnsubs.forEach(fn=>{try{fn();}catch{}});drawerUnsubs=[];}
async function renderDrawer(x,tab){
  const [profileSnap,threadsSnap]=await Promise.all([x.reeloId?getDoc(doc(db,"reelo_profiles",x.reeloId)):Promise.resolve(null),getDocs(query(collection(db,"support_threads"),where("bookingId","==",x.id)))]);const profile=profileSnap?.exists()?profileSnap.data():{};const threads=threadsSnap.docs.map(d=>({id:d.id,...d.data()}));
  const customerThread=threads.find(t=>t.userRole==="customer"||t.userId===x.customerId)||null;const reeloThread=threads.find(t=>t.userRole==="reelo"||t.userId===x.reeloId)||null;
  const tabs=[['overview','Overview'],['customer','Customer Chat'],['reelo','Reelo Chat'],['files','Files'],['timeline','Timeline']];
  const ses=sessionState(x);$("drawer-body").innerHTML=`<div class="drawer-booking-summary"><div><strong>${bookingRef(x.id)}</strong> ${statusHtml(ses.label,ses.tone)}<span>${esc(x.occasion||"Booking")} · ${dateText(x.scheduledDateTime||x.createdAt)}</span></div><button class="icon-btn" title="More">⋮</button></div><div class="drawer-tabs">${tabs.map(([k,l])=>`<button class="drawer-tab ${tab===k?'active':''}" data-dtab="${k}">${l}${k==='customer'&&customerThread?.unreadBySupport?' •':''}${k==='reelo'&&reeloThread?.unreadBySupport?' •':''}</button>`).join("")}</div><div id="drawer-tab-content"></div>`;
  document.querySelectorAll("[data-dtab]").forEach(b=>b.onclick=()=>renderDrawer(x,b.dataset.dtab));
  if(tab==="overview")renderOverviewTab(x,profile);else if(tab==="timeline")renderTimelineTab(x);else if(tab==="files")await renderFilesTab(x);else if(tab==="customer")await renderChatTab(x,customerThread,"customer");else if(tab==="reelo")await renderChatTab(x,reeloThread,"reelo");
}
function renderOverviewTab(x,profile){const del=deliveryState(x),ses=sessionState(x),pay=paymentState(x),availability=profile.availability||"Unknown";const deliveryPending=del.key==="pending_upload"||del.key==="uploading";$("drawer-tab-content").innerHTML=`<section class="drawer-section"><h3>Booking details</h3><div class="kv-list">${kv("Customer",x.customerName||x.customerEmail||x.customerId)}${kv("Reelo",x.reeloName||x.reeloEmail||"Not assigned")}${kv("Session",dateText(x.scheduledDateTime||x.createdAt)+` · ${x.durationMinutes||0} min`)}${kv("Location",x.location||"—")}${kv("Package",`${x.deliveryType==='edited'?'Edited':'Originals'} · ${x.occasion||'Booking'}`)}${kv("Amount",money(x.customerPrice||x.price))}${kv("Payment",pay.label+(x.paymentReference?` · ${String(x.paymentReference).slice(0,22)}…`:""))}</div></section><section class="drawer-section"><h3>Status & actions</h3><div class="state-stack"><div class="state-row"><span>Session status</span>${statusHtml(ses.label,ses.tone)}</div><div class="state-row"><span>Delivery status</span><span>${statusHtml(del.label,del.tone)} <small>${esc(del.detail)}</small></span></div><div class="state-row"><span>Reelo availability</span>${statusHtml(availability,availability==="Online"?"green":availability==="Busy"?"orange":"")}</div><div class="state-row"><span>Earnings</span>${x.earningsEligibleAt?statusHtml("Eligible","green"):statusHtml("Locked","orange")}</div></div><div class="reason-box"><textarea id="owner-reason" placeholder="Reason required for state-changing actions"></textarea></div><div class="action-stack">${["accepted","arrived","in_progress"].includes(x.status)?actionBtn("force_end_session","Force End Session → Pending Upload","Use if the physical session is stuck. Reelo goes Online.","primary"):""}${x.status==="completed"&&!['delivered','customer_confirmed'].includes(x.deliveryStatus)?actionBtn("move_to_pending_delivery","Repair → Pending Upload","Use if the session ended but delivery state is wrong.","warning"):""}${x.reeloId?actionBtn("mark_online","Mark Reelo Online","Emergency availability recovery only.","success"):""}${x.reeloId&&deliveryPending?actionBtn("notify_upload","Request Upload","Send the Reelo a content reminder.","secondary"):""}${["accepted","arrived"].includes(x.status)?actionBtn("return_to_search","Return to Matching","Release current Reelo and search again.","warning"):""}${paymentState(x).tone==="red"?actionBtn("flag_payment_review","Flag Payment Review","Keep payment under Operations review.","warning"):""}${["pending","failed","order_created"].includes(x.paymentStatus)?actionBtn("cancel_unpaid","Cancel Unpaid Booking","Only for a booking that has not started.","danger"):""}</div></section><section class="drawer-section"><h3>Operations note</h3><div class="chat-compose"><textarea id="ops-note" placeholder="Internal note — customers and Reelos cannot see this"></textarea><button class="btn primary" id="save-note">Add</button></div></section>`;
  document.querySelectorAll("[data-owner-action]").forEach(b=>b.onclick=()=>ownerAction(x,b.dataset.ownerAction));$("save-note").onclick=()=>saveNote(x.id);
}
function kv(label,value){return `<div class="kv"><span>${esc(label)}</span><strong>${esc(value??"—")}</strong></div>`;}
function actionBtn(action,title,desc,kind){return `<button class="btn ${kind}" data-owner-action="${action}">${esc(title)}<small>${esc(desc)}</small></button>`;}
async function ownerAction(x,action){const reason=$("owner-reason")?.value.trim()||"";const stateChanging=["force_end_session","move_to_pending_delivery","return_to_search","cancel_unpaid","mark_online"];if(stateChanging.includes(action)&&reason.length<5)return toast("Add a short reason first.");if(stateChanging.includes(action)&&!confirm("This changes the booking or Reelo state. Continue?"))return;try{
    if(action==="mark_online"){
      if(!x.reeloId)throw new Error("No Reelo is assigned.");await updateDoc(doc(db,"reelo_profiles",x.reeloId),{availability:"Online",updatedAt:serverTimestamp()});await addDoc(collection(db,"audit_logs"),{adminId:auth.currentUser.uid,adminEmail:auth.currentUser.email||"",action:"REELO_MARKED_ONLINE",targetType:"booking",targetId:x.id,reeloId:x.reeloId,reason,createdAt:serverTimestamp()});
    }else if(action==="notify_upload"){
      await httpsCallable(functions,"adminBookingAction")({bookingId:x.id,action:"notify_reelo",reason:reason||"Your session is complete. Please upload the required customer content before the delivery deadline. Earnings remain pending until delivery is accepted."});
    }else await httpsCallable(functions,"adminBookingAction")({bookingId:x.id,action,reason});
    toast("Operations action completed.");await openBooking(x.id,"overview");if(activePage==="overview"||activePage==="bookings"||activePage==="content")setTimeout(()=>loadPage(activePage),300);
  }catch(e){toast(friendly(e));}
}
async function saveNote(bookingId){const note=$("ops-note").value.trim();if(!note)return toast("Write an internal note first.");await addDoc(collection(db,"operations_notes"),{targetType:"booking",targetId:bookingId,note,adminId:auth.currentUser.uid,adminEmail:auth.currentUser.email||"",createdAt:serverTimestamp()});$("ops-note").value="";toast("Internal note saved.");}
function renderTimelineTab(x){const items=[["Booking created",x.createdAt],["Payment captured",x.paymentCapturedAt],["Reelo accepted",x.acceptedAt],["Reelo on the way",x.leftAt],["Arrived",x.arrivedAt],["Session started",x.startedAt],["Session completed",x.completedAt],["Content delivered",x.deliveredAt],["Customer accepted",x.deliveryConfirmedAt]].filter(([,v])=>v);$("drawer-tab-content").innerHTML=`<section class="drawer-section"><h3>Booking timeline</h3><div class="timeline">${items.length?items.map(([l,v])=>`<div class="timeline-item"><strong>${esc(l)}</strong><span>${esc(dateText(v))}</span></div>`).join(""):'<div class="empty">No lifecycle timestamps have been recorded.</div>'}</div></section>`;}
async function renderFilesTab(x){$("drawer-tab-content").innerHTML='<section class="drawer-section"><div class="loading">Loading delivered files…</div></section>';const snap=await getDocs(query(collection(db,"booking_media"),where("bookingId","==",x.id)));const items=snap.docs.map(d=>d.data());$("drawer-tab-content").innerHTML=`<section class="drawer-section"><h3>Content delivery</h3><div class="state-stack"><div class="state-row"><span>Delivery</span>${statusHtml(deliveryState(x).label,deliveryState(x).tone)}</div><div class="state-row"><span>Required</span><strong>${esc(x.requiredPhotoCount||"—")} photos · ${esc(x.requiredReelCount||"—")} reels</strong></div><div class="state-row"><span>Uploaded</span><strong>${items.filter(i=>i.type==='photo').length} photos · ${items.filter(i=>i.type==='reel').length} reels</strong></div></div></section><section class="drawer-section"><h3>Uploaded files</h3><div class="file-list">${items.length?items.map(i=>`<div class="file-item"><strong>${esc(i.fileName||i.type||"File")}</strong><span>${esc(i.type||"")} · ${esc(i.status||"active")} · ${esc(dateText(i.uploadedAt))}</span></div>`).join(""):'<div class="empty">No content has been uploaded for this booking.</div>'}</div></section>`;}
async function renderChatTab(x,thread,role){if(!thread){$("drawer-tab-content").innerHTML=`<section class="drawer-section"><h3>${role==='customer'?'Customer':'Reelo'} support</h3><div class="empty">No human support conversation is linked to this booking for the ${role}.</div></section>`;return;}$("drawer-tab-content").innerHTML=`<section class="drawer-section"><div class="state-row"><span>${role==='customer'?'Customer':'Reelo'} conversation</span>${statusHtml(thread.status||"open",thread.humanRequested?"orange":"blue")}</div><span class="sub">${esc(thread.userEmail||thread.userId||"")}</span></section><section class="drawer-section"><div id="drawer-chat" class="chat-box"><div class="loading">Loading conversation…</div></div><div class="quick"><button data-quick="I am reviewing this booking now. Please keep this chat open while I check it.">Reviewing now</button><button data-quick="Please tell me exactly what happened. Do not share passwords, OTPs, UPI PINs or full payment details.">Ask for details</button><button data-quick="Your session is complete. The booking is waiting for content upload and the Reelo can continue accepting new jobs.">Pending upload</button></div><div class="chat-compose"><textarea id="chat-reply" rows="2" placeholder="Reply as Reel It Support"></textarea><button class="btn primary" id="send-chat">Send</button></div><div class="action-stack"><button class="btn secondary" id="resolve-chat">Resolve conversation</button></div></section>`;
  const ref=doc(db,"support_threads",thread.id);const q=query(collection(ref,"messages"),orderBy("createdAt"));const unsub=onSnapshot(q,s=>{const box=$("drawer-chat");if(!box)return;box.innerHTML=s.docs.map(d=>{const m=d.data();const cls=m.senderType==="support"?"support":m.senderType==="system"||m.senderType==="assistant"?"system":"";return `<div class="bubble ${cls}">${esc(m.text||"")}</div>`;}).join("")||'<div class="empty">No messages.</div>';box.scrollTop=box.scrollHeight;});drawerUnsubs.push(unsub);document.querySelectorAll("[data-quick]").forEach(b=>b.onclick=()=>$("chat-reply").value=b.dataset.quick);$("send-chat").onclick=async()=>{const text=$("chat-reply").value.trim();if(!text)return;await addDoc(collection(ref,"messages"),{senderId:auth.currentUser.uid,senderType:"support",text,createdAt:serverTimestamp()});await setDoc(ref,{lastMessage:text,lastMessageBy:"support",lastMessageSender:"support",unreadBySupport:false,unreadByUser:true,status:"open",updatedAt:serverTimestamp()},{merge:true});$("chat-reply").value="";toast("Reply sent.");};$("resolve-chat").onclick=async()=>{await setDoc(ref,{status:"resolved",humanRequested:false,unreadBySupport:false,resolvedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});toast("Conversation resolved.");await renderDrawer(x,role);};}

async function loadSupport(){const snap=await getDocs(query(collection(db,"support_threads"),where("humanRequested","==",true)));const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));$("content").innerHTML=`<section class="panel"><div class="panel-head"><div><h3>Human support queue</h3><p>Customer and Reelo conversations stay private and link back to the exact booking.</p></div><button class="btn secondary" id="support-refresh">Refresh</button></div><div class="queue-list"><div class="queue-row head"><div>Priority</div><div>User</div><div>Booking</div><div>Role</div><div>Last message</div><div>Action</div></div>${rows.length?rows.map(t=>`<div class="queue-row"><div>${statusHtml(t.unreadBySupport?'Waiting':'Open',t.unreadBySupport?'orange':'blue')}</div><div><strong>${esc(t.userEmail||t.userId||'User')}</strong><span class="sub">${esc(timeAgo(t.updatedAt))}</span></div><div><button class="booking-link" data-support-booking="${esc(t.bookingId||'')}">${t.bookingId?bookingRef(t.bookingId):'No booking'}</button></div><div>${statusHtml(t.userRole||'user',t.userRole==='reelo'?'violet':'blue')}</div><div><span class="sub">${esc(t.lastMessage||'Human help requested')}</span></div><div><button class="btn primary" data-support="${esc(t.id)}">Reply</button></div></div>`).join(""):'<div class="empty">No human support conversations are waiting.</div>'}</div></section>`;$("support-refresh").onclick=()=>loadPage("support");document.querySelectorAll("[data-support-booking]").forEach(b=>b.onclick=()=>{if(b.dataset.supportBooking)openBooking(b.dataset.supportBooking,b.closest('.queue-row')?.querySelector('.status.violet')?'reelo':'customer');});document.querySelectorAll("[data-support]").forEach(b=>b.onclick=()=>openSupportThread(b.dataset.support));}
async function openSupportThread(id){const snap=await getDoc(doc(db,"support_threads",id));if(!snap.exists())return toast("Support thread not found.");const t={id,...snap.data()};if(t.bookingId)return openBooking(t.bookingId,t.userRole==="reelo"?"reelo":"customer");modal("Support conversation",`<p class="muted">This support case is not linked to a booking.</p><p><strong>${esc(t.userEmail||t.userId||'User')}</strong></p><p>${esc(t.lastMessage||'Human help requested')}</p>`);}

async function loadReelos(){const snap=await getDocs(collection(db,"reelo_profiles"));const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.name||a.email||a.id).localeCompare(String(b.name||b.email||b.id)));$("content").innerHTML=`${metricsHtml([{label:"Total Reelos",value:rows.length,icon:"◎",sub:"Profiles"},{label:"Online",value:rows.filter(x=>x.availability==='Online').length,icon:"●",sub:"Available now",good:true},{label:"Busy",value:rows.filter(x=>x.availability==='Busy').length,icon:"●",sub:"Active session",warn:true},{label:"Editing Approved",value:rows.filter(x=>x.editingApprovalStatus==='approved').length,icon:"✦",sub:"Eligible for Edited"},{label:"Needs Review",value:rows.filter(x=>x.verificationStatus==='pending_manual_review'||x.editingApprovalStatus==='pending_review').length,icon:"!",sub:"Manual review",warn:true}])}<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Reelo</th><th>Availability</th><th>Verified</th><th>Editing</th><th>Completed</th><th>Rating</th></tr></thead><tbody>${rows.map(x=>`<tr><td><span class="person">${esc(x.name||x.displayName||x.email||x.id)}</span><span class="sub">${esc(x.email||x.id)}</span></td><td>${statusHtml(x.availability||'Offline',x.availability==='Online'?'green':x.availability==='Busy'?'orange':'')}</td><td>${statusHtml(x.verified?'Approved':'Not approved',x.verified?'green':'orange')}</td><td>${statusHtml(x.editingApprovalStatus||'Not requested',x.editingApprovalStatus==='approved'?'violet':x.editingApprovalStatus==='pending_review'?'orange':'')}</td><td>${esc(x.completedBookings||0)}</td><td>${esc(x.rating||0)} ★</td></tr>`).join("")}</tbody></table></div></section>`;}

async function loadContent(){const bookings=await fetchBookings();const rows=bookings.filter(x=>['pending_upload','uploading','approval','dispute'].includes(deliveryState(x).key));$("content").innerHTML='<div id="booking-panel"></div>';renderBookingPanel(rows,"all");}
async function loadPayments(){const bookings=await fetchBookings();const rows=bookings.filter(x=>x.paymentStatus||x.razorpayOrderId||x.paymentReference);$("content").innerHTML='<div id="booking-panel"></div>';renderBookingPanel(rows,"all");}
async function loadRefunds(){const bookings=await fetchBookings();const rows=bookings.filter(x=>x.refundStatus&&x.refundStatus!=="not_required");$("content").innerHTML='<div id="booking-panel"></div>';renderBookingPanel(rows,"all");}
async function loadSOS(){const snap=await getDocs(query(collection(db,"sos_alerts"),orderBy("createdAt","desc"),limit(100)));const rows=snap.docs.map(d=>({id:d.id,...d.data()}));$("content").innerHTML=`<section class="panel"><div class="queue-list"><div class="queue-row head"><div>Priority</div><div>User</div><div>Booking</div><div>Status</div><div>Note</div><div>Action</div></div>${rows.length?rows.map(x=>`<div class="queue-row"><div>${statusHtml('SOS','red')}</div><div><strong>${esc(x.raisedByName||x.raisedByEmail||x.raisedBy||'User')}</strong></div><div><button class="booking-link" data-sos-booking="${esc(x.bookingId||'')}">${x.bookingId?bookingRef(x.bookingId):'—'}</button></div><div>${statusHtml(x.status||'active',x.status==='resolved'?'green':'red')}</div><div><span class="sub">${esc(x.note||'No note')}</span></div><div>${x.status!=='resolved'?`<button class="btn primary" data-sos-resolve="${esc(x.id)}">Resolve</button>`:''}</div></div>`).join(""):'<div class="empty">No SOS alerts.</div>'}</div></section>`;document.querySelectorAll("[data-sos-booking]").forEach(b=>b.onclick=()=>b.dataset.sosBooking&&openBooking(b.dataset.sosBooking));document.querySelectorAll("[data-sos-resolve]").forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,"sos_alerts",b.dataset.sosResolve),{status:"resolved",resolvedAt:serverTimestamp(),updatedAt:serverTimestamp()});loadPage("sos");});}
async function loadReports(){const snap=await getDocs(query(collection(db,"user_reports"),orderBy("createdAt","desc"),limit(100)));const rows=snap.docs.map(d=>({id:d.id,...d.data()}));renderSimpleTable("User reports",rows,[['reason','Reason'],['reporterEmail','Reporter'],['reportedUserName','Reported'],['status','Status'],['bookingId','Booking']],"user_reports");}
async function loadAccounts(){const snap=await getDocs(query(collection(db,"account_deletion_requests"),orderBy("requestedAt","desc"),limit(100)));const rows=snap.docs.map(d=>({id:d.id,...d.data()}));renderSimpleTable("Account deletion requests",rows,[['email','Account'],['status','Status'],['requestedAt','Requested'],['failureReason','Failure']],"account_deletion_requests");}
async function loadAudit(){const snap=await getDocs(query(collection(db,"audit_logs"),orderBy("createdAt","desc"),limit(150)));const rows=snap.docs.map(d=>({id:d.id,...d.data()}));renderSimpleTable("Privileged action audit log",rows,[['action','Action'],['adminEmail','Admin'],['targetId','Target'],['reason','Reason'],['createdAt','When']],"audit_logs");}
function renderSimpleTable(title,rows,cols){$("content").innerHTML=`<section class="panel"><div class="panel-head"><div><h3>${esc(title)}</h3><p>${rows.length} records</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr>${cols.map(([,l])=>`<th>${esc(l)}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.map(x=>`<tr>${cols.map(([k])=>`<td>${k==='bookingId'&&x[k]?`<button class="booking-link" data-generic-booking="${esc(x[k])}">${bookingRef(x[k])}</button>`:esc(x[k]?.toDate?dateText(x[k]):x[k]??'—')}</td>`).join("")}</tr>`).join(""):`<tr><td colspan="${cols.length}"><div class="empty">Nothing to show.</div></td></tr>`}</tbody></table></div></section>`;document.querySelectorAll("[data-generic-booking]").forEach(b=>b.onclick=()=>openBooking(b.dataset.genericBooking));}

async function runGlobalSearch(){const term=$("global-search").value.trim();if(!term)return toast("Enter a booking ID, short RIT reference, email or payment ID.");try{if(term.startsWith("RIT-")){const all=bookingCache.length?bookingCache:await fetchBookings();const found=all.find(x=>bookingRef(x.id)===term.toUpperCase());if(found)return openBooking(found.id);}const direct=await getDoc(doc(db,"bookings",term));if(direct.exists())return openBooking(direct.id);const all=bookingCache.length?bookingCache:await fetchBookings();const q=term.toLowerCase();const hits=all.filter(x=>bookingSearchText(x.id,x).includes(q));if(hits.length===1)return openBooking(hits[0].id);$("page-title").textContent="Search results";$("page-subtitle").textContent=`${hits.length} matching bookings`;$("content").innerHTML='<div id="booking-panel"></div>';renderBookingPanel(hits,"all");}catch(e){toast(friendly(e));}}
function modal(title,html){$("modal-content").innerHTML=`<div class="modal-body"><h3>${esc(title)}</h3>${html}</div>`;$("modal").showModal();}
